feature: add MixLoRA model support, improve inference speed and framework design
TUDB-Labs/multi-lora-fine-tune pull request #144
Opened 2024-01-05 06:50 UTC by mikecovlee

2024-01-06 03:10 UTC, merlintang commented on MixLoRA.md
> +
tell why this happen?

2024-01-06 06:40 UTC, yezhem commented
1. move the Prompter to prompter.py
2. prompter do not use hard code
3. del the utils.py

2024-01-06 06:50 UTC, yezhem requested changes

2024-01-06 06:50 UTC, yezhem commented on mlora/modelargs.py
> +    target_modules_: dict = None
dict -> Dict

2024-01-06 06:50 UTC, yezhem commented on mlora/modelargs.py
> +        self.lora_r_ = config["r"]
check the config param

2024-01-06 06:50 UTC, yezhem commented on mlora/modelargs.py
> +    def init(self, config: dict) -> "LoraConfig":
init -> from_configxxx

2024-01-07 04:48 UTC, mikecovlee commented on MixLoRA.md
> +
docs updated

2024-01-07 05:03 UTC, yezhem approved these changes
LGTM

2024-01-07 05:04 UTC, merged