Adding support for Qwen2(通义千问) and Mistral
TUDB-Labs/multi-lora-fine-tune pull request #182
Opened 2024-03-08 13:19 UTC by mikecovlee

2024-03-09 02:31 UTC, yezhem requested changes

2024-03-09 02:31 UTC, yezhem commented on mlora/trainer/trainer.py
> +        adapter_config["base_model_name_or_path"] = self.model_.name_or_path_
can we initially add base_model_name_or_path?

2024-03-09 02:31 UTC, yezhem commented on mlora/utils.py
> +            with open(lora_config.adapter_name_ + "/adapter_config.json", 'r', encoding='utf8') as fp:
add a comment or use function

2024-03-10 14:50 UTC, merlintang approved these changes
LGTM

2024-03-13 11:58 UTC, closed without merging