update the author lists
TUDB-Labs/multi-lora-fine-tune pull request #60
Opened 2023-10-05 12:48 UTC by merlintang

2023-10-05 13:34 UTC, LianxinGao approved these changes

2023-10-05 15:19 UTC, mikecovlee requested changes

2023-10-05 15:19 UTC, mikecovlee commented on README.md
> +  author = {Zhengmao Ye, Dengchen Li, Tingfen Lan, Yanbo Liang, Yexi Jiang, Jie Zuo, Hui Lu, Lei Duan, Mingjie Tang},
Typo: replace 'dengchen' with 'dengchun' plz.

2023-10-05 15:19 UTC, mikecovlee commented on README.md
> +  author = {Zhengmao Ye, Dengchen Li, Tingfen Lan, Yanbo Liang, Yexi Jiang, Jie Zuo, Hui Lu, Lei Duan, Mingjie Tang},
Also 'Tingfen' to 'Tingfeng' :)

2023-10-06 01:49 UTC, merlintang commented
fixed. @mikecovlee

2023-10-06 02:48 UTC, mikecovlee approved these changes
LGTM

2023-10-06 02:48 UTC, merged